########################
## LIVING ROOM LIGHTS ##
########################
- alias: Turn on living room lights
  hide_entity: true
  trigger:
    - platform: event
      event_type: LIVING_ROOM_LIGHTS_ON
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_lamps_switch
    - service: light.turn_on
      entity_id: light.dining_dimmer_level

- alias: Turn off living room lights
  hide_entity: true
  trigger:
    - platform: event
      event_type: LIVING_ROOM_LIGHTS_OFF
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_lamps_switch
    - service: light.turn_off
      entity_id: light.dining_dimmer_level
########################

####################
## MORNING LIGHTS ##
####################
- alias: Morning lights
  trigger:
    - platform: state
      entity_id: group.living_areas_motion
      to: "on"
  condition:
    - condition: time
      after: "05:00:00"
    - condition: sun
      before: sunrise
    - condition: state
      entity_id: switch.living_room_lamps_switch
      state: "off"
      for:
        minutes: 5
  action:
    - service: automation.trigger
      entity_id: automation.turn_on_living_room_lights
####################

#####################
## SUN ROOM MOTION ##
#####################
- alias: Sun room motion lights
  trigger:
    platform: state
    entity_id: binary_sensor.sun_room_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: light.sun_room_dimmer_level
      state: "off"
    - condition: or
      conditions:
        - condition: sun
          before: sunrise
        - condition: sun
          after: sunset
  action:
    service: light.turn_on
    entity_id: light.sun_room_dimmer_level

- alias: End sun room motion lights
  trigger:
    platform: state
    entity_id: binary_sensor.sun_room_motion
    to: "off"
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: light.sun_room_dimmer_level
      state: "on"
  action:
    service: light.turn_off
    entity_id: light.sun_room_dimmer_level
#####################

######################
## BACKYARD LIGHTS ##
######################
- alias: Turn off left on backyard lights
  trigger:
    - platform: state
      entity_id: switch.backyard_lights_switch
      to: "on"
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.sun_room_door
      to: "off"
      for:
        minutes: 5
  action:
    service: switch.turn_off
    entity_id: switch.backyard_lights_switch

- alias: Turn on backyard lights for door
  trigger:
    platform: state
    entity_id: binary_sensor.sun_room_door
    to: "on"
  condition:
    - condition: or
      conditions:
        - condition: sun
          before: sunrise
        - condition: sun
          after: sunset
  action:
    service: switch.turn_on
    entity_id: switch.backyard_lights_switch

- alias: Office balcony lights follow backyard lights on state
  trigger:
    platform: state
    entity_id: switch.backyard_lights_switch
    to: "on"
  action:
    service: switch.turn_on
    entity_id: switch.office_balcony_lights_switch

- alias: Office balcony lights follow backyard lights off state
  trigger:
    platform: state
    entity_id: switch.backyard_lights_switch
    to: "off"
  action:
    service: switch.turn_off
    entity_id: switch.office_balcony_lights_switch

- alias: Turn off left on office balcony lights
  trigger:
    - platform: state
      entity_id: switch.office_balcony_lights_switch
      to: "on"
      for:
        minutes: 20
  action:
    service: switch.turn_off
    entity_id: switch.office_balcony_lights_switch

#######################

##############################################
## OUTSIDE FRONT LIGHTS FROM SUNSET TO 11PM ##
##############################################
- alias: Sunset outside front lights
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: switch.turn_on
      entity_id: switch.outside_front_lights_switch

- alias: End Sunset Outside Front Lights
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.outside_front_lights_switch
##############################################

######################################
## LIGHTS ON WHEN ARRIVING AT NIGHT ##
######################################
- alias: Lights on when arriving (connected)
  trigger:
    - platform: state
      entity_id: group.my_devices
      to: "home"
  condition:
    - condition: sun
      after: sunset
  action:
    - service: automation.trigger
      entity_id: automation.turn_on_living_room_lights

- alias: Lights on when arriving (door)
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door
      to: "on"
  condition:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: group.my_devices
      state: "away"
  action:
    - service: automation.trigger
      entity_id: automation.turn_on_living_room_lights

######################################

######################################
## LIGTHS ON WHEN HOME NEAR SUNSET ##
######################################
- alias: Sunset lamps on when home
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  condition:
    - condition: state
      entity_id: group.my_devices
      state: "home"
    - condition: state
      entity_id: group.living_areas_motion
      state: "on"
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_lamps_switch

- alias: Sunset living room lights on when home
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition:
    - condition: state
      entity_id: group.my_devices
      state: "home"
    - condition: state
      entity_id: group.living_areas_motion
      state: "on"
  action:
    - service: automation.trigger
      entity_id: automation.turn_on_living_room_lights

######################################

#######################################################
## Living room mantel lamps follow living room lamps ##
#######################################################
- alias: Living room mantel lamps follow living room lamps on state
  trigger:
    platform: state
    entity_id: switch.living_room_lamps_switch
    to: "on"
  action:
    service: switch.turn_on
    entity_id: switch.living_room_mantel_lamps_switch

- alias: Living room mantel lamps follow living room lamps off state
  trigger:
    platform: state
    entity_id: switch.living_room_lamps_switch
    to: "off"
  action:
    service: switch.turn_off
    entity_id: switch.living_room_mantel_lamps_switch

############################
### Harmony Home Control ###
############################
# Relies heavily on emulated_roku: https://gitlab.com/mindig.marton/ha-emulated_roku
# Valid external commands: https://sdkdocs.roku.com/display/sdkdoc/External+Control+API#ExternalControlAPI-KeypressKeyValues

- alias: Prepare lights for going to bed
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: BackSpace
  condition:
    - condition: time
      after: "21:00:00"
    - condition: sun
      before: sunrise
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_lamps_switch
    - service: light.turn_on
      data:
        entity_id: light.dining_dimmer_level
        brightness: 90
    - service: switch.turn_off
      entity_id: switch.outside_front_lights_switch
    - service: switch.turn_on
      entity_id: switch.backyard_lights_switch
    - delay: '00:05:00'
    - service: light.turn_on # restore original brightness so next time we turn it on it's not dim
      data:
        entity_id: light.dining_dimmer_level
        brightness: 255
    - service: light.turn_off
      entity_id: light.dining_dimmer_level

- alias: Emulated Roku Command Up/Living Room Lamps
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: Up
  action:
    - service: switch.toggle
      entity_id: switch.living_room_lamps_switch

- alias: Emulated Roku Command Down/Dining Dimmer
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: Down
  action:
    - service: light.toggle
      entity_id: light.dining_dimmer_level

- alias: Emulated Roku Command Left/Living Room Mantel Lamps
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: Left
  action:
    - service: switch.toggle
      entity_id: switch.living_room_mantel_lamps_switch

- alias: Emulated Roku Command Right/Backyard Lights
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: Right
  action:
    - service: switch.toggle
      entity_id: switch.backyard_lights_switch

- alias: Emulated Roku Command Play/Start KEXP On Receiver
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: Play
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.living_room_audio
        media_content_id: "http://live-mp3-128.kexp.org/kexp128.mp3"
        media_content_type: "audio/mp4"

- alias: Emulated Roku Command Back/Stop Chromecast
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: Back
  action:
    - service: media_player.media_stop
      entity_id: media_player.living_room_audio


######################################
### Front door locking automations ###
######################################
- alias: Lock front door deadbolt when door closed
  hide_entity: true
  trigger:
    - platform: event
      event_type: LOCK_FRONT_DOOR
  condition:
    - condition: state
      entity_id: lock.front_door_deadbolt_locked
      state: "unlocked"
    - condition: state
      entity_id: binary_sensor.front_door
      state: "off"
  action:
    - service: lock.lock
      entity_id: lock.front_door_deadbolt_locked

- alias: Notify could not lock front door because it was left open
  hide_entity: true
  trigger:
    - platform: event
      event_type: LOCK_FRONT_DOOR
  condition:
    - condition: state
      entity_id: lock.front_door_deadbolt_locked
      state: "unlocked"
    - condition: state
      entity_id: binary_sensor.front_door
      state: "on"
  action:
    - service: notify.twilio
      data:
        target: !secret kyle_phone
        message: "Unable to lock front door because it has been left open"
        title: "Cannot lock front door"

- alias: Lock front door when nobody is home
  trigger:
    - platform: state
      entity_id: group.my_devices
      to: "not_home"
  action:
    - event: LOCK_FRONT_DOOR

- alias: Lock front door at 10 PM 
  trigger:
    - platform: time
      at: "22:00:00"
  action:
    - event: LOCK_FRONT_DOOR

- alias: Warn front door unlocked by guest code
  trigger:
    - platform: numeric_state
      entity_id: lock.front_door_deadbolt_locked
      value_template: '{{ (state.attributes.lock_status).split(" ")[-1] | int }}'
      above: 1 # 1 is our code, and > 1 means one of the many guest codes
  action:
    - service: notify.twilio
      data:
        target: !secret kyle_phone
        message: 'Warning! Front door unlocked by guest user code {{ (states.lock.front_door_deadbolt_locked.attributes.lock_status).split(" ")[-1] }}'

- alias: Warn front door deadbolt low battery
  trigger:
    - platform: numeric_state
      entity_id:  zwave.front_door_deadbolt
      value_template: '{{ state.attributes.battery_level }}'
      below: 15
  action:
    - service: persistent_notification.create
      data:
        title: "Low battery!"
        message: 'Front door deadbolt down to {{ states.zwave.front_door_deadbolt.attributes.battery_level }}%. Replace batteries.'
