########################
## LIVING ROOM LIGHTS ##
########################
- alias: Turn on living room lights
  hide_entity: true
  trigger:
    - platform: event
      event_type: LIVING_ROOM_LIGHTS_ON
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_lamps_switch
    - service: light.turn_on
      entity_id: light.dining_dimmer_level

- alias: Turn off living room lights
  hide_entity: true
  trigger:
    - platform: event
      event_type: LIVING_ROOM_LIGHTS_OFF
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_lamps_switch
    - service: light.turn_off
      entity_id: light.dining_dimmer_level
########################

####################
## MORNING LIGHTS ##
####################
- alias: Morning lights
  trigger:
    - platform: state
      entity_id: group.living_areas_motion
      to: "on"
  condition:
    - condition: time
      after: "05:00:00"
    - condition: sun
      before: sunrise
    - condition: state
      entity_id: switch.living_room_lamps_switch
      state: "off"
      for:
        minutes: 5
  action:
    - service: automation.trigger
      entity_id: automation.turn_on_living_room_lights
####################

#####################
## SUN ROOM MOTION ##
#####################
- alias: Sun room motion lights
  trigger:
    platform: state
    entity_id: binary_sensor.sun_room_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: light.sun_room_dimmer_level
      state: "off"
    - condition: or
      conditions:
        - condition: sun
          before: sunrise
        - condition: sun
          after: sunset
  action:
    - service: light.turn_on
      entity_id: light.sun_room_dimmer_level
    - delay: "00:05:00"
    - service: light.turn_off
      entity_id: light.sun_room_dimmer_level

#####################

######################
## BACKYARD LIGHTS ##
######################
- alias: Turn off left on backyard lights
  trigger:
    - platform: state
      entity_id: switch.backyard_lights_switch
      to: "on"
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.sun_room_door
      to: "off"
      for:
        minutes: 5
  action:
    service: switch.turn_off
    entity_id: switch.backyard_lights_switch

- alias: Turn on backyard lights for door
  trigger:
    platform: state
    entity_id: binary_sensor.sun_room_door
    to: "on"
  condition:
    - condition: or
      conditions:
        - condition: sun
          before: sunrise
        - condition: sun
          after: sunset
  action:
    service: switch.turn_on
    entity_id: switch.backyard_lights_switch

- alias: Office balcony lights follow backyard lights on state
  trigger:
    platform: state
    entity_id: switch.backyard_lights_switch
    to: "on"
  action:
    service: switch.turn_on
    entity_id: switch.office_balcony_lights_switch

- alias: Office balcony lights follow backyard lights off state
  trigger:
    platform: state
    entity_id: switch.backyard_lights_switch
    to: "off"
  action:
    service: switch.turn_off
    entity_id: switch.office_balcony_lights_switch

- alias: Turn off left on office balcony lights
  trigger:
    - platform: state
      entity_id: switch.office_balcony_lights_switch
      to: "on"
      for:
        minutes: 20
  action:
    service: switch.turn_off
    entity_id: switch.office_balcony_lights_switch

#######################

##############################################
## OUTSIDE FRONT LIGHTS FROM SUNSET TO 11PM ##
##############################################
- alias: Sunset outside front lights
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: switch.turn_on
      entity_id: switch.outside_front_lights_switch

- alias: End Sunset Outside Front Lights
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.outside_front_lights_switch
##############################################

######################################
## LIGHTS ON WHEN ARRIVING AT NIGHT ##
######################################
- alias: Lights on when arriving (connected)
  trigger:
    - platform: state
      entity_id: group.my_devices
      to: "home"
  condition:
    - condition: sun
      after: sunset
  action:
    - service: automation.trigger
      entity_id: automation.turn_on_living_room_lights

- alias: Lights on when arriving (door)
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door
      to: "on"
  condition:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: group.my_devices
      state: "away"
  action:
    - service: automation.trigger
      entity_id: automation.turn_on_living_room_lights

######################################

######################################
## LIGTHS ON WHEN HOME NEAR SUNSET ##
######################################
- alias: Sunset lamps on when home
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  condition:
    - condition: state
      entity_id: group.my_devices
      state: "home"
    - condition: state
      entity_id: group.living_areas_motion
      state: "on"
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_lamps_switch

- alias: Sunset living room lights on when home
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition:
    - condition: state
      entity_id: group.my_devices
      state: "home"
    - condition: state
      entity_id: group.living_areas_motion
      state: "on"
  action:
    - service: automation.trigger
      entity_id: automation.turn_on_living_room_lights

######################################

#######################################################
## Living room aux lights follow living room lamps ##
#######################################################
- alias: Living room aux lights follow living room lamps on state
  trigger:
    platform: state
    entity_id: switch.living_room_lamps_switch
    to: "on"
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_mantel_lamps_switch
    - service: light.turn_on
      entity_id: light.living_room_light

- alias: Living room aux lights follow living room lamps off state
  trigger:
    platform: state
    entity_id: switch.living_room_lamps_switch
    to: "off"
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_mantel_lamps_switch
    - service: light.turn_off
      entity_id: light.living_room_light

############################
### Harmony Home Control ###
############################
# Relies heavily on emulated_roku: https://gitlab.com/mindig.marton/ha-emulated_roku
# Valid external commands: https://sdkdocs.roku.com/display/sdkdoc/External+Control+API#ExternalControlAPI-KeypressKeyValues

- alias: Prepare lights for going to bed
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: BackSpace
  condition:
    - condition: time
      after: "21:00:00"
    - condition: sun
      before: sunrise
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_lamps_switch
    - service: light.turn_on
      data:
        entity_id: light.dining_dimmer_level
        brightness: 90
    - service: switch.turn_off
      entity_id: switch.outside_front_lights_switch
    - service: switch.turn_on
      entity_id: switch.backyard_lights_switch
    - delay: '00:05:00'
    - service: light.turn_on # restore original brightness so next time we turn it on it's not dim
      data:
        entity_id: light.dining_dimmer_level
        brightness: 255
    - service: light.turn_off
      entity_id: light.dining_dimmer_level

- alias: Emulated Roku Command Up/Living Room Lamps
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: Up
  action:
    - service: switch.toggle
      entity_id: switch.living_room_lamps_switch

- alias: Emulated Roku Command Down/Dining Dimmer
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: Down
  action:
    - service: light.toggle
      entity_id: light.dining_dimmer_level

- alias: Emulated Roku Command Left/Living Room Mantel Lamps
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: Left
  action:
    - service: switch.toggle
      entity_id: switch.living_room_mantel_lamps_switch

- alias: Emulated Roku Command Right/Backyard Lights
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: Right
  action:
    - service: switch.toggle
      entity_id: switch.backyard_lights_switch

- alias: Emulated Roku Command Play/Start KEXP On Receiver
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: Play
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.living_room_audio
        media_content_id: "http://live-mp3-128.kexp.org/kexp128.mp3"
        media_content_type: "audio/mp4"

- alias: Emulated Roku Command Back/Stop Chromecast
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      type: keypress
      key: Back
  action:
    - service: media_player.media_stop
      entity_id: media_player.living_room_audio


######################################
### Front door locking automations ###
######################################
- alias: Lock front door deadbolt when door closed
  hide_entity: true
  trigger:
    - platform: event
      event_type: LOCK_FRONT_DOOR
  condition:
    - condition: state
      entity_id: lock.front_door_deadbolt_locked
      state: "unlocked"
    - condition: state
      entity_id: binary_sensor.front_door
      state: "off"
  action:
    - service: lock.lock
      entity_id: lock.front_door_deadbolt_locked

- alias: Notify could not lock front door because it was left open
  hide_entity: true
  trigger:
    - platform: event
      event_type: LOCK_FRONT_DOOR
  condition:
    - condition: state
      entity_id: lock.front_door_deadbolt_locked
      state: "unlocked"
    - condition: state
      entity_id: binary_sensor.front_door
      state: "on"
  action:
    - service: notify.twilio
      data:
        target: !secret kyle_phone
        message: "Unable to lock front door because it has been left open"
        title: "Cannot lock front door"

- alias: Lock front door when nobody is home
  trigger:
    - platform: state
      entity_id: group.my_devices
      to: "not_home"
  action:
    - event: LOCK_FRONT_DOOR

- alias: Lock front door at 10 PM 
  trigger:
    - platform: time
      at: "22:00:00"
  action:
    - event: LOCK_FRONT_DOOR

- alias: Warn front door unlocked by guest code
  trigger:
    - platform: numeric_state
      entity_id: lock.front_door_deadbolt_locked
      value_template: '{{ (state.attributes.lock_status).split(" ")[-1] | int }}'
      above: 1 # 1 is our code, and > 1 means one of the many guest codes
  action:
    - service: notify.twilio
      data:
        target: !secret kyle_phone
        message: 'Warning! Front door unlocked by guest user code {{ (states.lock.front_door_deadbolt_locked.attributes.lock_status).split(" ")[-1] }}'

## warn multiple failure attempts within a short period of time

- alias: Warn front door deadbolt low battery
  trigger:
    - platform: numeric_state
      entity_id:  zwave.front_door_deadbolt
      value_template: '{{ state.attributes.battery_level }}'
      below: 15
  action:
    - service: persistent_notification.create
      data:
        title: "Low battery!"
        message: 'Front door deadbolt down to {{ states.zwave.front_door_deadbolt.attributes.battery_level }}%. Replace batteries.'


#######################
### Fan Automations ###
#######################

- alias: When temperature between upstairs and downstairs differs, turn on fan for 30 minutes
  trigger:
    - platform: template
      value_template: "{{ ((states.sensor.upstairs_temperature.state | float) - (states.sensor.home_temperature.state | float)) | abs > 3.0 }}"
  condition:
    - condition: state
      entity_id: fan.living_room
      state: "off"
  action:
    - service: fan.turn_on
      entity_id: fan.living_room
    - service: fan.set_speed
      entity_id: fan.living_room
      data:
        speed: 6
    - delay: '00:15:00'
    - service: fan.turn_off
      entity_id: fan.living_room

- alias: When thermostat set to cool, set fan direction forward
  trigger:
    - platform: state
      entity_id: climate.home 
      to: "cool" 
  action:
    - service: fan.set_direction
      entity_id: fan.living_room
      data:
        direction: forward

- alias: When thermostate set to heat, set fan direction reverse
  trigger:
    - platform: state
      entity_id: climate.home
      to: "heat"
  action:
    - service: fan.set_direction
      entity_id: fan.living_room
      data:
        direction: reverse

- alias: When HVAC fan running, turn on fan
  trigger:
    - platform: template
      value_template: "{{ states.climate.home.attributes.fan == 'on' }}"
  condition:
    - condition: state
      entity_id: fan.living_room
      state: "off"
  action:
    - service: fan.turn_on
      entity_id: fan.living_room
    - delay: "00:15:00"
    - service: fan.turn_off
      entity_id: fan.living_room 

- alias: Turn off fan when nobody is home
  trigger:
    - platform: state
      entity_id: group.my_devices
      to: "not_home"
      for:
        minutes: 10 
  condition:
    - condition: state
      entity_id: fan.living_room
      state: "on"
  action:
    - service: fan.turn_off
      entity_id: fan.living_room_fan

- alias: Turn off fan when left on late at night
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    - condition: state
      entity_id: fan.living_room
      state: "on"
  action:
    - service: fan.turn_off
      entity_id: fan.living_room


##############################
### Janitorial Automations ###
##############################

- alias: Renew Let's Encrypt certificate
  trigger:
  - platform: time
    at: '00:03:00' # 3am
  action:
  - service: hassio.addon_stop
    data:
      addon: core_nginx_proxy
  - service: hassio.addon_start
    data:
      addon: core_letsencrypt
  - delay: '00:05:00' # 5 minutes
  - service: hassio.addon_start
    data:
      addon: core_nginx_proxy
