homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude:  !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 315
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  whitelist_external_dirs:
    - '/tmp'
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  server_port: 8123
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# # Weather prediction
# sensor:
#   - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
alert: !include alerts.yaml

# Enable configurator in frontend
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    # Intentionally not port forwarded or exposed, so only locally accessible
    url: https://hassio.local:3218

alarmdecoder:
  device:
    type: socket
    host: 192.168.86.12
    port: 10000
  panel_display: on
  zones:
    09:
      name: 'Front Door'
      type: 'door'
      rfid: '0322355'
    10:
      name: 'Garage Door'
      type: 'door'
      rfid: '0402108'
    11:
      name: 'Laundry Room Door'
      type: 'door'
      rfid: '0627375'
    12:
      name: 'Master Bedroom Door'
      type: 'door'
      rfid: '0526985'
    13:
      name: 'Sun Room Door'
      type: 'door'
      rfid: '0358656'
    14:
      name: 'Office Door'
      type: 'door'
      rfid: '0876836'
    15:
      name: 'Foyer Motion'
      type: 'motion'
      rfid: '0518434'
    16:
      name: 'Sun Room Motion'
      type: 'motion'
      rfid: '0505218'
    17:
      name: 'First Floor Smoke Zone'
      type: 'smoke'
      rfid: '0641332'
    18:
      name: 'Second Floor Smoke Zone'
      type: 'smoke'
      rfid: '0571026'
    19:
      name: 'Basement Smoke Zone'
      type: 'smoke'
      rfid: '0119565'

ecobee:
  api_key: !secret ecobee_api_key
  
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config: !include zwave_device_config.yaml

sensor:
  - platform: wunderground
    api_key: !secret wunderground_api_key
    monitored_conditions:
      - temp_f
      - feelslike_f
      - weather_1d
      - temp_high_record_f
      - temp_high_1d_f
      - temp_low_1d_f
      - temp_low_record_f
  - platform: sense
    email: !secret sense_email
    password: !secret sense_password
    monitored_conditions:
      - daily_usage
      - weekly_usage
      - monthly_usage
      - active_usage
      - devices
  - platform: mqtt
    name: outside_temperature
    state_topic: "homeassistant/sensor/rtl443"
    unit_of_measurement: "°F"
    value_template: '{{ ((value_json.temperature_C * 9 / 5) + 32)|round(1) }}'
  - platform: mqtt
    name: outside_humidity
    state_topic: "homeassistant/sensor/rtl443"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity }}'

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

notify:
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
  - name: Twilio
    platform: twilio_sms
    from_number: !secret twilio_from_number
  - name: Twilio Call
    platform: twilio_call
    from_number: !secret twilio_from_number
  - name: Contact Kyle
    platform: group
    services:
      - service: twilio
        data:
          target: !secret kyle_phone
      - service: twilio_call
        data:
          target: !secret kyle_phone
  - name: Push Notification
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

google_domains:
  domain: !secret google_ddns_domain
  username: !secret google_ddns_username
  password: !secret google_ddns_password
 
device_tracker:
  - platform: bluetooth_tracker

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: samsungtv
    host: 192.168.86.121
    port: 8001

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_assistant_agent_user_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - group
    - script
  entity_config:
    group.all_automations:
      expose: false
    group.all_devices:
      expose: false
    group.all_doors:
      expose: false
    group.all_motion:
      expose: false
    group.all_switches:
      expose: false
    group.all_smoke:
      expose: false
    group.home_comfort:
      expose: false
    group.home_security:
      expose: false
    group.living_areas_motion:
      expose: false
    group.my_devices:
      expose: false
    group.sun_room_speakers:
      expose: false
    group.water_sensors:
      expose: false
    group.weather_overview:
      expose: false
    switch.car_port_lights_switch:
      name: Car Port Lights
    light.dining_dimmer_level:
      name: Dining Dimmer
    switch.living_room_lamps_switch:
      name: Living Room Lamps
    switch.outside_front_lights_switch:
      name: Outside Front Lights
    switch.sun_room_speakers_switch:
      name: Sun Room Speakers
    light.sun_room_dimmer_level:
      name: Sun Room Dimmer
    switch.backyard_lights_switch:
      name: Backyard Lights
    group.all_lights:
      name: All Lights

binary_sensor:
  - platform: template
    sensors:
      first_floor_smoke:
        device_class: smoke
        friendly_name: "First Floor Smoke"
        value_template: >-
          {{ states.sensor.alarm_panel_display.state|trim == "FIRE 17" }}
      second_floor_smoke:
        device_class: smoke
        friendly_name: "Second Floor Smoke"
        value_template: >-
          {{ states.sensor.alarm_panel_display.state|trim == "FIRE 18" }}
      basement_smoke:
        device_class: smoke
        friendly_name: "Basement Smoke"
        value_template: >-
          {{ states.sensor.alarm_panel_display.state|trim == "FIRE 19" }}

hdmi_cec:
  devices:
    TV: 0.0.0.0
    Receiver: 3.0.0.0
    Switch: 3.2.0.0
    Hassio: 3.3.0.0
    MiBox: 3.4.0.0

shell_command:
  zwave_stick_disco_off: echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/ttyACM0
  zwave_stick_disco_on: echo -e -n "\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50" > /dev/ttyACM0

mqtt:
  broker: core-mosquitto

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.86.140

emulated_roku:
  host_ip: 192.168.86.15
  listen_ports:
    - 8060

# logger:
